version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-184-73-249-9.compute-1.amazonaws.com
            database: deno9lgpdnntmv
            user: ificpevkjumiwc
            password: 09047e48cf38f5989afb2f9a4660e3ffe4df4281eead85cdcb99f0eed6953471
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
